### ISSUE TITLE
Unwanted Windows line endings

### ISSUE THREAD

**Issue by bt-s** [bt-s/dinnerplanner-html#4]
The standard new-line character is \n, however, in Windows sometimes the ^M new-line character is used instead.

I am not 100%, but I think that I have fixed the issue in ee0c854 (see nes1983's answer on https://stackoverflow.com/questions/1889559/git-diff-to-ignore-m).

Maybe you should still locally execute the following command: git config --global core.autocrlf true

**Comment by Envl** [comment]
problem tackled
