### ISSUE TITLE
ESlint

### ISSUE THREAD

**Issue by bt-s** [bt-s/dinnerplanner-html#46]
It seems like you have been using a linter for JS in your text editor.
This is no problem, as long as we both use the same one.

The one that you have used removes all semi-colons after statements.
I am personally against this practice, since it can cause really strange behaviour in minified JS files.
Maybe we should configure and share a linter together when we start working on Lab 4.

In the meantime, what do you think of the guidelines in the following source?
https://news.codecademy.com/your-guide-to-semicolons-in-javascript/

**Comment by Envl** [comment]
Yeah, for the sake of consistency, we should keep these semicolons.
